name: Build Cronet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Chromium code
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --branch=main --depth=1
          export PATH="$PATH:$PWD/depot_tools"

          mkdir chromium && cd chromium
          fetch --nohooks --no-history chromium

      - name: Build Cronet
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          ./build/install-build-deps.sh --no-prompt
          gclient runhooks
          
          ./components/cronet/tools/cr_cronet.py gn
          autoninja -C out/Debug cronet_package
          ./components/cronet/tools/cr_cronet.py gn --release
          autoninja -C out/Release cronet_package

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cronet
          path: chromium/src/out
